name: Python Tests

on:
  push:
    branches: [ main, feature/actions, feature/refactor ]
  pull_request:
    branches: [ main, feature/actions, feature/refactor ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up environment variables
      run: echo "HEADLESS=true" >> $GITHUB_ENV  # Define sua própria variável

    - name: Set up Chrome
      run: |
        sudo apt-get update
        sudo apt-get install -y google-chrome-stable

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run tests
      run: pytest