name: Python Tests

on:
  push:
    branches: [ main, feature/actions, feature/refactor ]
  pull_request:
    branches: [ main, feature/actions, feature/refactor ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up environment variables
      run: echo "HEADLESS=true" >> $GITHUB_ENV

    - name: Set up Chrome
      run: |
        sudo apt-get update
        sudo apt-get install -y google-chrome-stable

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install allure-pytest

    - name: Run tests
      run: pytest --alluredir=allure-results

    - name: Install Allure
      run: |
        sudo apt-get install -y unzip
        mkdir -p ~/allure
        wget https://github.com/allure-framework/allure2/releases/download/2.19.0/allure-2.19.0.zip -O ~/allure/allure.zip
        unzip ~/allure/allure.zip -d ~/allure/
        sudo ln -s ~/allure/allure-2.19.0/bin/allure /usr/bin/allure

    - name: Generate Allure Report
      run: allure generate allure-results --clean -o allure-report
